<template>
  <div class="app-container zycck-config">
    <el-alert class="page-tip" title="未来职业猜猜看配置" type="info" :closable="false" description="先维护职业，再维护竞猜题目。每个职业只绑定一道题；固定模式配置 1 个候选题，随机池模式配置 3 个候选题。" />
    <el-tabs v-model="activeTab" type="border-card">
      <el-tab-pane label="职业维护" name="careers">
        <el-table :data="categories" border stripe class="full-table category-list"><el-table-column prop="sortOrder" label="排序" width="75" align="center" /><el-table-column prop="name" label="职业大类" min-width="220" /><el-table-column label="抽题模式" width="140" align="center"><template slot-scope="scope"><el-tag :type="scope.row.drawMode === 'random' ? 'warning' : 'success'">{{ drawModeText(scope.row.drawMode) }}</el-tag></template></el-table-column><el-table-column label="题目数" width="100" align="center"><template slot-scope="scope">{{ scope.row.questionCount || 0 }} / 10</template></el-table-column><el-table-column label="候选数" width="100" align="center"><template slot-scope="scope">{{ scope.row.candidateCount || 0 }} / {{ scope.row.drawMode === 'random' ? 3 : 1 }}</template></el-table-column><el-table-column label="操作" width="120" align="center"><template slot-scope="scope"><el-button type="text" size="mini" @click="openCategoryDialog(scope.row)">编辑</el-button></template></el-table-column></el-table>
        <div class="category-cards"><el-card v-for="item in categories" :key="item.categoryId" class="category-card" shadow="hover" :class="{ active: String(careerQuery.categoryId) === String(item.categoryId) }" @click.native="selectCategory(item.categoryId)"><div class="category-card-name">{{ item.name }}</div><div class="category-card-meta">{{ item.questionCount || 0 }} 个职业 · 候选 {{ item.candidateCount || 0 }}/{{ item.drawMode === 'random' ? 3 : 1 }}</div></el-card></div>
        <div class="section-toolbar"><div class="toolbar-left"><el-select v-model="careerQuery.categoryId" clearable filterable size="small" placeholder="全部职业大类" @change="loadCareers"><el-option v-for="item in categories" :key="item.categoryId" :label="item.name" :value="item.categoryId" /></el-select><el-input v-model="careerQuery.keyword" clearable size="small" class="keyword" placeholder="搜索职业名称" @keyup.enter.native="loadCareers" /><el-button type="primary" size="small" icon="el-icon-search" @click="loadCareers">查询</el-button></div><div><el-button type="success" size="small" icon="el-icon-plus" @click="openCareerDialog()">新增职业</el-button><el-button size="small" icon="el-icon-refresh" @click="loadCareers">刷新</el-button></div></div>
        <el-table v-loading="careerLoading" :data="careers" border stripe class="full-table"><el-table-column type="index" label="#" width="58" align="center" /><el-table-column prop="categoryName" label="职业大类" min-width="190" /><el-table-column prop="careerName" label="职业名称" min-width="220" /><el-table-column label="是否已绑定题目" width="150" align="center"><template slot-scope="scope"><el-tag :type="scope.row.careerQuestionId ? 'success' : 'warning'">{{ scope.row.careerQuestionId ? '已绑定 1 道' : '未绑定' }}</el-tag></template></el-table-column><el-table-column label="状态" width="100" align="center"><template slot-scope="scope"><el-tag :type="String(scope.row.status) === '0' ? 'success' : 'info'">{{ String(scope.row.status) === '0' ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column prop="sortOrder" label="排序" width="80" align="center" /><el-table-column label="操作" width="230" align="center" fixed="right"><template slot-scope="scope"><el-button type="text" size="mini" @click="editCareerQuestion(scope.row)">编辑职业</el-button><el-button type="text" size="mini" @click="editQuestion(scope.row)">编辑题目</el-button><el-button type="text" size="mini" class="danger-text" @click="removeCareer(scope.row)">删除职业</el-button></template></el-table-column></el-table>
        <el-empty v-if="!careerLoading && !careers.length" description="暂无职业，请先新增职业" />
      </el-tab-pane>
      <el-tab-pane label="题目维护" name="questions">
        <div class="category-cards"><el-card v-for="item in categories" :key="item.categoryId" class="category-card" shadow="hover" :class="{ active: String(questionQuery.categoryId) === String(item.categoryId) }" @click.native="selectQuestionCategory(item.categoryId)"><div class="category-card-name">{{ item.name }}</div><div class="category-card-meta">{{ drawModeText(item.drawMode) }}</div></el-card></div>
        <div class="section-toolbar"><div class="toolbar-left"><el-select v-model="questionQuery.categoryId" clearable filterable size="small" placeholder="全部职业大类" @change="loadQuestions"><el-option v-for="item in categories" :key="item.categoryId" :label="item.name" :value="item.categoryId" /></el-select><el-input v-model="questionQuery.keyword" clearable size="small" class="keyword" placeholder="搜索题干/职业名称" @keyup.enter.native="loadQuestions" /><el-button type="primary" size="small" icon="el-icon-search" @click="loadQuestions">查询</el-button></div><div><el-button type="success" size="small" icon="el-icon-plus" @click="openQuestionDialog()">新增题目</el-button><el-button size="small" icon="el-icon-refresh" @click="loadQuestions">刷新</el-button></div></div>
        <el-table v-loading="questionLoading" :data="questions" border stripe class="full-table question-table"><el-table-column type="index" label="#" width="58" align="center" /><el-table-column prop="categoryName" label="职业大类" min-width="190" /><el-table-column prop="careerName" label="绑定职业" min-width="180" /><el-table-column label="题干/场景图" min-width="280"><template slot-scope="scope"><div class="stem-cell"><el-image v-if="scope.row.questionImageUrl" :src="scope.row.questionImageUrl" fit="cover" class="thumb" :preview-src-list="[scope.row.questionImageUrl]" /><span>{{ scope.row.questionText || '猜猜以上内容是下面哪个职业的工作场景？' }}</span></div></template></el-table-column><el-table-column label="A-D 职业选项" min-width="300"><template slot-scope="scope"><div class="options-cell"><span>A. {{ careerName(scope.row.optionACareerId) || scope.row.optionA || '未设置' }}</span><span>B. {{ careerName(scope.row.optionBCareerId) || scope.row.optionB || '未设置' }}</span><span>C. {{ careerName(scope.row.optionCCareerId) || scope.row.optionC || '未设置' }}</span><span>D. {{ careerName(scope.row.optionDCareerId) || scope.row.optionD || '未设置' }}</span></div></template></el-table-column><el-table-column label="正确选项" width="100" align="center"><template slot-scope="scope"><el-tag type="success">{{ scope.row.correctOptionKey || '-' }}</el-tag></template></el-table-column><el-table-column label="候选池" width="100" align="center"><template slot-scope="scope"><el-tag :type="isCandidate(scope.row.drawCandidate) ? 'warning' : 'info'">{{ isCandidate(scope.row.drawCandidate) ? '候选题' : '普通题' }}</el-tag></template></el-table-column><el-table-column label="状态" width="90" align="center"><template slot-scope="scope">{{ String(scope.row.status) === '0' ? '启用' : '停用' }}</template></el-table-column><el-table-column label="操作" width="160" align="center" fixed="right"><template slot-scope="scope"><el-button type="text" size="mini" @click="preview(scope.row)">预览</el-button><el-button type="text" size="mini" @click="editQuestion(scope.row)">编辑</el-button></template></el-table-column></el-table>
        <pagination v-show="questionTotal > 0" :total="questionTotal" :page.sync="questionQuery.pageNum" :limit.sync="questionQuery.pageSize" @pagination="loadQuestions" /><el-empty v-if="!questionLoading && !questions.length" description="暂无题目，请先维护职业并新增题目" />
      </el-tab-pane>
    </el-tabs>

    <el-dialog :title="careerForm.careerQuestionId ? '编辑职业' : '新增职业'" :visible.sync="careerDialogVisible" width="560px" append-to-body><el-form ref="careerForm" :model="careerForm" :rules="careerRules" label-width="100px"><el-form-item label="职业大类" prop="categoryId"><el-select v-model="careerForm.categoryId" filterable placeholder="请选择职业大类" style="width: 100%"><el-option v-for="item in categories" :key="item.categoryId" :label="item.name" :value="item.categoryId" /></el-select></el-form-item><el-form-item label="职业名称" prop="careerName"><el-input v-model="careerForm.careerName" maxlength="100" show-word-limit /></el-form-item><el-form-item label="排序"><el-input-number v-model="careerForm.sortOrder" :min="1" :max="999" /></el-form-item><el-form-item label="状态"><el-switch v-model="careerEnabled" active-text="启用" inactive-text="停用" /></el-form-item></el-form><div slot="footer"><el-button @click="careerDialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="submitCareer">保存</el-button></div></el-dialog>

        <el-dialog :title="questionForm.careerQuestionId ? '编辑题目' : '新增题目'" :visible.sync="questionDialogVisible" width="820px" append-to-body><el-alert title="题目规则" type="info" :closable="false" class="dialog-tip" description="四个选项必须选择 4 个不同职业；正确选项对应的职业即为本题绑定职业。所有职业均通过中文下拉选择。" /><el-form ref="questionForm" :model="questionForm" :rules="questionRules" label-width="110px" size="small"><el-form-item label="职业大类" prop="categoryId"><el-select v-model="questionForm.categoryId" filterable placeholder="请选择职业大类" style="width: 100%" @change="questionCategoryChanged"><el-option v-for="item in categories" :key="item.categoryId" :label="item.name + '（' + drawModeText(item.drawMode) + '）'" :value="item.categoryId" /></el-select></el-form-item><el-form-item label="绑定职业" prop="careerQuestionId"><el-select v-model="questionForm.careerQuestionId" filterable placeholder="请选择本题绑定职业" style="width: 100%"><el-option v-for="career in categoryCareerOptions" :key="career.careerQuestionId" :label="career.careerName" :value="career.careerQuestionId" /></el-select></el-form-item><el-form-item label="题干"><el-input v-model="questionForm.questionText" type="textarea" :rows="2" maxlength="300" show-word-limit placeholder="不填写时使用默认题干" /></el-form-item><el-form-item label="题目场景图"><ImageUpload v-model="questionForm.questionImageUrl" :limit="1" /></el-form-item><el-divider content-position="left">职业选项（中文下拉）</el-divider><el-row v-for="option in optionRows" :key="option.key" :gutter="12"><el-col :span="24"><el-form-item :label="'选项 ' + option.label" :prop="option.career"><el-select v-model="questionForm[option.career]" filterable clearable placeholder="请选择职业名称" style="width: 100%"><el-option v-for="career in careerOptions" :key="career.careerQuestionId" :label="career.careerName" :value="career.careerQuestionId" /></el-select></el-form-item></el-col></el-row><el-form-item label="正确选项" prop="correctOptionKey"><el-radio-group v-model="questionForm.correctOptionKey"><el-radio v-for="key in optionKeys" :key="key" :label="key">{{ key }}</el-radio></el-radio-group></el-form-item><el-form-item label="候选池"><el-switch v-model="questionForm.drawCandidate" active-text="加入当前大类抽题候选池" /></el-form-item><el-form-item label="状态"><el-switch v-model="questionEnabled" active-text="启用" inactive-text="停用" /></el-form-item></el-form><div slot="footer"><el-button @click="questionDialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="submitQuestion">保存</el-button></div></el-dialog>

    <el-dialog title="题目预览" :visible.sync="previewVisible" width="660px" append-to-body><div v-if="previewQuestion" class="question-preview"><el-tag type="info">{{ previewQuestion.categoryName || categoryName(previewQuestion.categoryId) }}</el-tag><h3>{{ previewQuestion.questionText || '猜猜以上内容是下面哪个职业的工作场景？' }}</h3><el-image v-if="previewQuestion.questionImageUrl" :src="previewQuestion.questionImageUrl" fit="contain" class="preview-image" :preview-src-list="[previewQuestion.questionImageUrl]" /><div v-for="item in previewOptions" :key="item.key" class="preview-option">{{ item.key }}. {{ item.text || careerName(item.careerId) || '未设置' }}<el-tag v-if="item.key === previewQuestion.correctOptionKey" size="mini" type="success">正确答案</el-tag></div></div></el-dialog>
  </div>
</template>

<script>
import { listCategories, listCareerQuestions, saveCareerQuestion, deleteCareerQuestion, zycckErrorMessage } from '@/api/zycck'
const emptyQuestion = () => ({ categoryId: null, careerQuestionId: null, careerName: '', questionText: '', questionImageUrl: '', optionA: '', optionB: '', optionC: '', optionD: '', optionACareerId: null, optionBCareerId: null, optionCCareerId: null, optionDCareerId: null, correctOptionKey: 'A', drawCandidate: false, status: '0', sortOrder: 1 })
export default {
  name: 'ZycckConfig',
  data() { return { activeTab: 'careers', categoryLoading: false, careerLoading: false, questionLoading: false, saving: false, categories: [], careers: [], questions: [], allQuestions: [], questionTotal: 0, careerDialogVisible: false, questionDialogVisible: false, previewVisible: false, previewQuestion: null, careerForm: {}, questionForm: emptyQuestion(), careerQuery: { categoryId: null, keyword: null }, questionQuery: { pageNum: 1, pageSize: 10, categoryId: null, keyword: null }, optionKeys: ['A', 'B', 'C', 'D'], optionRows: [{ key: 'A', label: 'A', text: 'optionA', career: 'optionACareerId' }, { key: 'B', label: 'B', text: 'optionB', career: 'optionBCareerId' }, { key: 'C', label: 'C', text: 'optionC', career: 'optionCCareerId' }, { key: 'D', label: 'D', text: 'optionD', career: 'optionDCareerId' }], careerRules: { categoryId: [{ required: true, message: '请选择职业大类', trigger: 'change' }], careerName: [{ required: true, message: '请输入职业名称', trigger: 'blur' }] }, questionRules: { categoryId: [{ required: true, message: '请选择职业大类', trigger: 'change' }], careerQuestionId: [{ required: true, message: '请选择绑定职业', trigger: 'change' }], correctOptionKey: [{ required: true, message: '请选择正确选项', trigger: 'change' }] } } },
  computed: { careerEnabled: { get() { return String(this.careerForm.status || '0') === '0' }, set(value) { this.careerForm.status = value ? '0' : '1' } }, questionEnabled: { get() { return String(this.questionForm.status || '0') === '0' }, set(value) { this.questionForm.status = value ? '0' : '1' } }, careerOptions() { return this.allQuestions }, categoryCareerOptions() { return this.allQuestions.filter(item => String(item.categoryId) === String(this.questionForm.categoryId)) }, previewOptions() { return this.optionRows.map(item => ({ key: item.key, text: this.previewQuestion && this.previewQuestion[item.text], careerId: this.previewQuestion && this.previewQuestion[item.career] })) } },
  created() { this.loadCategories() },
  methods: {
    categoryName(id) { const item = this.categories.find(category => String(category.categoryId) === String(id)); return item ? item.name : '' }, drawModeText(mode) { return mode === 'random' ? '随机池，需3题' : '固定，需1题' }, isCandidate(value) { return value === true || value === 1 || String(value) === '1' }, careerName(id) { const item = this.allQuestions.find(career => String(career.careerQuestionId) === String(id)); return item ? item.careerName : '' },
    loadCategories() { this.categoryLoading = true; listCategories({ pageNum: 1, pageSize: 50, gameType: 'zycck' }).then(res => { this.categories = res.rows || res.data || []; this.loadAllQuestions(); this.loadCareers(); this.loadQuestions() }).catch(error => this.$modal.msgError(zycckErrorMessage(error))).finally(() => { this.categoryLoading = false }) },
    loadAllQuestions() { return listCareerQuestions({ pageNum: 1, pageSize: 1000, gameType: 'zycck' }).then(res => { this.allQuestions = res.rows || res.data || [] }).catch(error => this.$modal.msgError(zycckErrorMessage(error))) },
    loadCareers() { this.careerLoading = true; listCareerQuestions({ pageNum: 1, pageSize: 1000, categoryId: this.careerQuery.categoryId, keyword: this.careerQuery.keyword, gameType: 'zycck' }).then(res => { const rows = res.rows || res.data || []; this.careers = rows.map(item => ({ ...item, categoryName: item.categoryName || this.categoryName(item.categoryId) })) }).catch(error => this.$modal.msgError(zycckErrorMessage(error))).finally(() => { this.careerLoading = false }) },
    loadQuestions() { this.questionLoading = true; listCareerQuestions({ ...this.questionQuery, gameType: 'zycck' }).then(res => { const rows = res.rows || res.data || []; this.questions = rows.map(item => ({ ...item, categoryName: item.categoryName || this.categoryName(item.categoryId) })); this.questionTotal = res.total || this.questions.length }).catch(error => this.$modal.msgError(zycckErrorMessage(error))).finally(() => { this.questionLoading = false }) },
    openCareerDialog(row) { this.careerForm = row ? { ...row } : { categoryId: this.careerQuery.categoryId, careerQuestionId: null, careerName: '', sortOrder: this.careers.length + 1, status: '0' }; this.careerDialogVisible = true; this.$nextTick(() => this.$refs.careerForm && this.$refs.careerForm.clearValidate()) }, editCareerQuestion(row) { this.openCareerDialog(row) },
    submitCareer() { this.$refs.careerForm.validate(valid => { if (!valid) return; this.saving = true; saveCareerQuestion({ ...this.careerForm, gameType: 'zycck', careerOnly: true }).then(() => { this.$modal.msgSuccess('职业保存成功'); this.careerDialogVisible = false; return this.loadAllQuestions() }).then(() => { this.loadCareers(); this.loadQuestions() }).catch(error => this.$modal.msgError(zycckErrorMessage(error))).finally(() => { this.saving = false }) }) },
    openQuestionDialog(row) { this.questionForm = row ? { ...emptyQuestion(), ...row, drawCandidate: this.isCandidate(row.drawCandidate) } : emptyQuestion(); if (!this.questionForm.categoryId && this.questionQuery.categoryId) this.questionForm.categoryId = this.questionQuery.categoryId; this.questionDialogVisible = true; this.$nextTick(() => this.$refs.questionForm && this.$refs.questionForm.clearValidate()) }, editQuestion(row) { this.activeTab = 'questions'; this.openQuestionDialog(row) }, questionCategoryChanged() { if (!this.questionForm.careerQuestionId || !this.categoryCareerOptions.some(item => String(item.careerQuestionId) === String(this.questionForm.careerQuestionId))) this.questionForm.careerQuestionId = null },
    submitQuestion() { this.$refs.questionForm.validate(valid => { if (!valid) return; const optionIds = this.optionRows.map(item => String(this.questionForm[item.career] || '')); if (optionIds.some(id => !id) || new Set(optionIds).size !== 4) return this.$modal.msgWarning('四个选项必须选择 4 个不同职业'); const category = this.categories.find(item => String(item.categoryId) === String(this.questionForm.categoryId)); const count = this.allQuestions.filter(item => this.isCandidate(item.drawCandidate) && String(item.categoryId) === String(this.questionForm.categoryId) && String(item.careerQuestionId) !== String(this.questionForm.careerQuestionId)).length + (this.questionForm.drawCandidate ? 1 : 0); const required = category && category.drawMode === 'random' ? 3 : 1; if (count > required) return this.$modal.msgWarning(this.drawModeText(category && category.drawMode) + '，候选题不能超过 ' + required + ' 道'); const boundCareer = this.allQuestions.find(item => String(item.careerQuestionId) === String(this.questionForm.careerQuestionId)); const payload = { ...this.questionForm, careerName: boundCareer ? boundCareer.careerName : this.questionForm.careerName, optionA: this.careerName(this.questionForm.optionACareerId), optionB: this.careerName(this.questionForm.optionBCareerId), optionC: this.careerName(this.questionForm.optionCCareerId), optionD: this.careerName(this.questionForm.optionDCareerId), drawCandidate: this.questionForm.drawCandidate ? '1' : '0', gameType: 'zycck' }; this.saving = true; saveCareerQuestion(payload).then(() => { this.$modal.msgSuccess('题目保存成功'); this.questionDialogVisible = false; return this.loadAllQuestions() }).then(() => { this.loadCareers(); this.loadQuestions() }).catch(error => this.$modal.msgError(zycckErrorMessage(error))).finally(() => { this.saving = false }) }) },
    removeCareer(row) { this.$modal.confirm('删除职业“' + row.careerName + '”及其对应题目？删除后不可恢复。').then(() => deleteCareerQuestion(row.careerQuestionId)).then(() => { this.$modal.msgSuccess('职业及对应题目已删除'); this.loadAllQuestions(); this.loadCareers(); this.loadQuestions(); this.loadCategories() }).catch(error => { if (error) this.$modal.msgError(zycckErrorMessage(error)) }) },
    selectCategory(id) { this.careerQuery.categoryId = id; this.loadCareers() }, selectQuestionCategory(id) { this.questionQuery.categoryId = id; this.loadQuestions() },
    preview(row) { this.previewQuestion = row; this.previewVisible = true }
  }
}
</script>

<style scoped>
.page-tip { margin-bottom: 16px; }
.category-cards { display: flex; gap: 12px; margin-bottom: 14px; overflow-x: auto; }
.category-card { flex: 1 0 170px; cursor: pointer; border-top: 3px solid #dcdfe6; }
.category-card.active { border-top-color: #409eff; }
.category-card-name { font-size: 16px; font-weight: 600; }
.category-card-meta { margin-top: 8px; color: #909399; font-size: 12px; }
.section-toolbar { display: flex; justify-content: space-between; align-items: center; gap: 16px; margin-bottom: 14px; }
.toolbar-left { display: flex; align-items: center; gap: 10px; }
.toolbar-left .el-select { width: 220px; }
.keyword { width: 240px; }
.full-table { width: 100%; }
.question-table .cell { white-space: normal; line-height: 1.5; }
.stem-cell { display: flex; align-items: center; gap: 10px; min-height: 48px; }
.thumb { width: 52px; height: 42px; flex: 0 0 52px; border-radius: 4px; background: #f5f7fa; }
.options-cell { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 14px; color: #606266; }
.dialog-tip { margin-bottom: 16px; }
.question-preview h3 { margin: 14px 0; }
.preview-image { display: block; width: 100%; height: 220px; margin-bottom: 14px; background: #f5f7fa; }
.preview-option { display: flex; justify-content: space-between; padding: 10px 12px; margin: 6px 0; border: 1px solid #ebeef5; border-radius: 4px; }
@media (max-width: 900px) { .section-toolbar { align-items: flex-start; flex-direction: column; } .toolbar-left { flex-wrap: wrap; width: 100%; } .keyword { flex: 1; min-width: 160px; } }
</style>
